### ISSUE TITLE
Can't mount efs filesystem error

### ISSUE THREAD

**Issue by pahud** [pahud/cdk-efs-assets#100]
In some cases the deployment will fail due to the efs mount timeout.

Please comment below if you have similar issue like this.

<img width="939" alt="圖片" src="https://user-images.githubusercontent.com/278432/108580393-47990080-7366-11eb-8938-2811144ef71c.png">

<img width="1059" alt="圖片" src="https://user-images.githubusercontent.com/278432/108581211-9300de00-7369-11eb-8e0c-5d94f44802f9.png">

**Comment by semsphy** [comment]
@pahud , I'm about to report this problem too.

**Comment by pahud** [comment]
I believe this could be the underlying service issue between lambda service and efs service

My CDK testing code is a simple lambda function with efs mount. When I successfully deploy it and manually click the **Test** button in the lambda console, I got exactly the same the error message. However, if I click the test button again, it will always work.

Feel free to test the sample code in your environment and let me know if you have the same issue. Thanks.

```ts
import * as cdk from '@aws-cdk/core';
import * as efs from '@aws-cdk/aws-efs';
import * as ec2 from '@aws-cdk/aws-ec2';
import * as lambda from '@aws-cdk/aws-lambda';

export interface DemoProps { }

export class Demo extends cdk.Construct {
  constructor(scope: cdk.Construct, id: string) {
    super(scope, id)

    const vpc = ec2.Vpc.fromLookup(stack, 'Vpc', { isDefault: true })

    const fileSystem = new efs.FileSystem(stack, 'Filesystem', {
      vpc,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    })
  
    // create a new access point from the filesystem
    const accessPoint = fileSystem.addAccessPoint('AccessPoint', {
      // set /export/lambda as the root of the access point
      path: '/export/lambda',
      // as /export/lambda does not exist in a new efs filesystem, the efs will create the directory with the following createAcl
      createAcl: {
        ownerUid: '1001',
        ownerGid: '1001',
        permissions: '750',
      },
      // enforce the POSIX identity so lambda function will access with this identity
      posixUser: {
        uid: '1001',
        gid: '1001',
      },
    });

    new lambda.Function(this, 'MyFunc', {
      runtime: lambda.Runtime.PYTHON_3_7,
      handler: 'index.handler',
      code: new lambda.InlineCode(`
import json
def handler(event, context):
      return {
        'statusCode': 200,
        'body': json.dumps('Hello CDK from Lambda!')
      }`),
      vpc,
      filesystem: lambda.FileSystem.fromEfsAccessPoint(accessPoint, '/mnt/msg'),
    });
  }
}

const devEnv = {
  account: process.env.CDK_DEFAULT_ACCOUNT,
  region: process.env.CDK_DEFAULT_REGION,
};

const app = new cdk.App();

const stack = new cdk.Stack(app, 'my-stack-dev', { env: devEnv });

new Demo(stack, 'Demo')

app.synth();

```

<img width="1765" alt="圖片" src="https://user-images.githubusercontent.com/278432/108582308-59ca6d00-736d-11eb-8734-459ca41bb454.png">

**Comment by semsphy** [comment]
The demo stack has no problem in my environment. I'm using cdk `1.89.0 (build df7253c)`

![image](https://user-images.githubusercontent.com/423396/108582783-f427b200-7367-11eb-92c5-e44929d2c272.png)

**Comment by pahud** [comment]
> The demo stack has no problem in my environment. I'm using cdk `1.89.0 (build df7253c)`
> 
> ![image](https://user-images.githubusercontent.com/423396/108582783-f427b200-7367-11eb-92c5-e44929d2c272.png)

Which region you are deploying to? Make sure you click the `Test` button in the lambda console to invoke the function manually.

**Comment by semsphy** [comment]
> > The demo stack has no problem in my environment. I'm using cdk `1.89.0 (build df7253c)`
> > ![image](https://user-images.githubusercontent.com/423396/108582783-f427b200-7367-11eb-92c5-e44929d2c272.png)
> 
> Which region you are deploying to? Make sure you click the `Test` button in the lambda console to invoke the function manually.

`Singapore - ap-southeast-1`

**Comment by semsphy** [comment]
I got the `timeout` issue, while I was testing in the complicated stack combine with the ECS task.

**Comment by pahud** [comment]
> I got the `timeout` issue, while I was testing in the complicated stack combine with the ECS task.

I am guessing this is simply due to the lambda integration with efs so I create a simple `Hello CDK` greeting function above. Can you test the Hello function above and make sure you click the `Test` button manually? Did it work correctly when you first click the Test button?

**Comment by semsphy** [comment]
You were right, the first click is `KO`.

![image](https://user-images.githubusercontent.com/423396/108583063-c3487c80-7369-11eb-98b6-4c96efd7a07f.png)

**Comment by jialechan** [comment]
<img width="1146" alt="9B81180A-0335-44A3-8292-FD7EC8D4BAEC" src="https://user-images.githubusercontent.com/7006540/108587138-edf7fc80-738c-11eb-9095-abf776aa10fd.png">
I got the timeout issue too.
It does not happen every time, and if it happens, it only happens during the first testing the lambda function.

**Comment by jochemkleine** [comment]
Thanks for the replies. Your sample code posted above builds successfully for me. Like others noted, running the lambda initially gives an error, and it works from the second run going forwards (which is fine).

However, that doesn't solve my original issue; when I try to implement a simple ` SyncedAccessPoint ` my ` cdk deploy ` times out and fails with the error specified [here](https://github.com/pahud/cdk-efs-assets/issues/98)

**Comment by pahud** [comment]
> Thanks for the replies. Your sample code posted above builds successfully for me. Like others noted, running the lambda initially gives an error, and it works from the second run going forwards (which is fine).
> 
> However, that doesn't solve my original issue; when I try to implement a simple `SyncedAccessPoint` my `cdk deploy` times out and fails with the error specified [here](https://github.com/pahud/cdk-efs-assets/issues/98)

Actually the root cause of the issue you encountered is relevant to this issue. When you create `SyncedAccessPoint`, under the covers a custom resource will be created, which will execute the lambda function with efs mount immediately after the lambda function is created. However, as the lambda function with efs mount could timeout, the `SyncedAccessPoint` will not be able to be created due to the efs mount timeout error.

**Comment by semsophy** [comment]
@pahud , Do you have any workarounds to this issue? Thank.

**Comment by pahud** [comment]
> @pahud , Do you have any workarounds to this issue? Thank.

No, but I will try reach out internally. I am also considering to use [fargate-run-task](https://github.com/pahud/cdk-fargate-run-task) as a replacement as fargate support efs as well.

@stephenwiebe  @guan840912 wdyt?

**Comment by guan840912** [comment]
Fargate replace Lambda -> sounds good 👍

**Comment by pahud** [comment]
Guys I've refactored the design with AWS Fargate support in this PR.
https://github.com/pahud/cdk-efs-assets/pull/113

It works great in my environment. Let me know if you have any feedbacks.

**Comment by semsphy** [comment]
I will test this weekend, @pahud. Really appreciate.

**Comment by stephenwiebe** [comment]
> When you create SyncedAccessPoint, under the covers a custom resource will be created, which will execute the lambda function with efs mount immediately after the lambda function is created. However, as the lambda function with efs mount could timeout, the SyncedAccessPoint will not be able to be created due to the efs mount timeout error.

Shouldn't this line:

https://github.com/pahud/cdk-efs-assets/blob/76b397e07cd84184fce6bdf900a52178f53e6799/src/synced-access-point.ts#L431

introduce a dependency such that the lambda function is not executed until the mountpoint is available?

**Comment by pahud** [comment]
> > When you create SyncedAccessPoint, under the covers a custom resource will be created, which will execute the lambda function with efs mount immediately after the lambda function is created. However, as the lambda function with efs mount could timeout, the SyncedAccessPoint will not be able to be created due to the efs mount timeout error.
> 
> Shouldn't this line:
> 
> https://github.com/pahud/cdk-efs-assets/blob/76b397e07cd84184fce6bdf900a52178f53e6799/src/synced-access-point.ts#L418
> 
> introduce a dependency such that the lambda function is not executed until the mountpoint is available?


The dependency is working as expected, but somehow there seems to be a bug when we first invoke the lambda function with efs mount.

You can try this https://github.com/pahud/cdk-efs-assets/issues/100#issuecomment-782549481 and see if you encounter the error. That is why we moved to fargate.

**Comment by semsophy** [comment]
@pahud, it is OK now. The issue can be closed now. Appreciate!

**Comment by y4nnick** [comment]
I am still getting the same error. Is there a work around?
