### ISSUE TITLE
CDK 2.0 support

### ISSUE THREAD

**Issue by mats16** [pahud/cdk-efs-assets#173]
cdk-efs-assets does not work well with CDK 2.0.0-rc.5

Need to use aws-cdk-lib.

**Comment by pahud** [comment]
> cdk-efs-assets does not work well with CDK 2.0.0-rc.5
> 
> Need to use aws-cdk-lib.

Yeah we are not planning to support  CDK2 until it goes GA.

**Comment by MattWatWork** [comment]
@pahud any chance of bumping this up to CDK2 now?
