### ISSUE TITLE
Should this module expose its functionality as a SyncedAccessPoint?

### ISSUE THREAD

**Issue by stephenwiebe** [pahud/cdk-efs-assets#55]
Something I was thinking about as I was adding the S3 functionality: should this module actually bring the AccessPoint that it writes to (and deletes from as a precursor step) as a new resource defined within the scope of this stack instead of being passed in? For the S3 content that I was extracting, I found that I had to delete anything else that might already exist and then extract to the root path in the access point because when using the access point in an ECS task, you must reference it from the root (you can't specify an access point and then mount a directory from _below_ the access point root as your desired mount point). This is potentially dangerous if someone is creating the access point and managing it outside the scope of this module - if any data is changed and then deleted when they weren't expecting it to be deleted.

So it seems like a SyncedAccessPoint construct might make sense where we manage the AccessPoint entirely within the scope of this module. That would make the separation of concerns more clear, and also feels cleaner in some way. Rather than the user defining some construct that syncs some data to an access point that they pass in, they would instead be instantiating a SyncedAccessPoint construct that behaves like an IAccessPoint with some additional functionality.

I'm thinking something along these lines:

```
export interface SyncedAccessPointProps extends AccessPointProps {
  readonly syncSource: SyncSource;
  readonly syncOptions: SyncOptions;
}

export class SyncedAccessPoint extends AccessPoint implements IAccessPoint {
  constructor(scope: Construct, id: string, props: SyncedAccessPointProps) {
    super(scope, id, props);

    if (props.syncSource == SyncSource.GITHUB) {
      // create lambda handler and everything else here
    } else if (props.syncSource == SyncSource.S3_ARCHIVE) {

    }
}
```

So the SyncedAccessPoint would behave exactly like a normal AccessPoint with the additional feature that data is initially synced to it (and potentially resynced on update of source).

What do you think?

**Comment by pahud** [comment]
HI @stephenwiebe 

Sorry for the late reply. Sounds interesting. Let's draft a PR?
