### ISSUE TITLE
Sync github private repo

### ISSUE THREAD

**Issue by semsphy** [pahud/cdk-efs-assets#96]
Hello @pahud,

Thank you for creating such a great package.

Would you please guide me on how to sync the private repo?

Thanks,

**Comment by pahud** [comment]
Hi

This library doesn't support private repo at this moment.

However, if you look into the lambda function, under the covers it just execute the `git clone` for you:

https://github.com/pahud/cdk-efs-assets/blob/92f824f880850294b095e87e89629424cbd9dd9c/lambda-handler/github-sync/index.py#L58

I believe it's possible to support private repo as long as we can pass the personal access token securely to lambda function 
and let lambda execute similar command with the PAT against the https repo URI.

Unfortunately, I have to ETA for this feature but any PRs are welcome.

**Comment by semsphy** [comment]
Thank you for your prompt response. Let me check this out

**Comment by pahud** [comment]
Let's leave this issue open.

I believe it's possible to

`git clone https://username:password@github.com/pahud/cdk-efs-assets.git`

while `password` is the PAT stored in secret manager.

@guan840921 wdyt?

**Comment by pahud** [comment]
or maybe 

git clone https://oauth-key-goes-here@github.com/username/repo.git  

we probably need to check the document.

**Comment by semsphy** [comment]
> or maybe
> 
> `git clone https://oauth-key-goes-here@github.com/username/repo.git `
> 
> we probably need to check the document.

Yup, I will check the doc, right now. Thanks.

**Comment by semsphy** [comment]
`git clone https://oauth-key-goes-here@github.com/username/repo.git`, it works.
