### ISSUE TITLE
Error on deploy: EFSMountFailureException: The function couldn't mount the Amazon EFS file system

### ISSUE THREAD

**Issue by jochemkleine** [pahud/cdk-efs-assets#98]
Hey,

**First of all,** thanks for making this package; it definitely solves a problem I and many others have ran into before. 

I'm just trying to get a simple example with s3 working. The main code looks like so (very very similar to the s3 example in the readme): 

    import { SyncSource, SyncedAccessPoint } from 'cdk-efs-assets';

    const fs = new efs.FileSystem(this, 'FileSystem', {
      vpc,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    const bucket = s3.Bucket.fromBucketName(this, 'efssyncbucket', 'efssyncbucket');

    const efsAccessPoint = new SyncedAccessPoint(this, 'EfsAccessPoint', {
      fileSystem: fs,
      path: '/demo-s3',
      createAcl: {
        ownerGid: '1001',
        ownerUid: '1001',
        permissions: '0755',
      },
      posixUser: {
        uid: '1001',
        gid: '1001',
      },
      syncSource: SyncSource.s3Archive({
        vpc: vpc,
        bucket: bucket,
        zipFilePath: 's3test.zip',
      }),
    }); 

**However**, I keep running into the following error after 2-3 minutes of building after issueing the cdk deploy command:

`
AWS::CloudFormation::CustomResource | EfsAccessPointSyncTrigger737A66CC
Failed to create resource. EFSMountFailureException: The function couldn't mount the Amazon EFS file system with access point arn:aws:elasticfilesystem:eu-west-1:
870629590110:access-point/fsap-066f27e5a73d9a71e.
`

Any idea what could be causing this error, or how to fix it? I'm just trying to get a super simple example working for now :) 

Thanks.

**Comment by pahud** [comment]
Thanks for the feedback. We are investigating this issue here https://github.com/pahud/cdk-efs-assets/issues/100

**Comment by y4nnick** [comment]
Any updates on this?

**Comment by pahud** [comment]
Closing this issue in favor of #100
